---
  - name: Add jessie backports repository
    apt_repository:
      repo: deb http://ftp.debian.org/debian jessie-backports main
      state: present
    tags: install
    become: yes

  - name: Install certbot pin on jessie-backports
    apt:
      name: certbot
      state: present
      default_release: jessie-backports
    tags: install
    become: yes

  - name: Ensure webroot exists
    file:
      path: "{{ letsencrypt_webroot_path }}"
      state: directory
      follow: yes
    become: yes

  - name: Attempt to get the certificate using the webroot authenticator
    command: "/usr/bin/letsencrypt -n --agree-tos --rsa-key-size 4096 --text -a webroot -w {{ letsencrypt_webroot_path }}/{{ item }} -d {{ item }} --email {{ letsencrypt_email }} {% if letsencrypt_server is defined %}--server {{ letsencrypt_server }}{% endif %} --expand certonly"
    become: yes
    args:
      creates: "/etc/letsencrypt/live/{{ item }}"
    with_items: "{{ letsencrypt_cert_domains }}"

  - name: Install renewal cron
    become: yes
    cron:
      name: "Let's Encrypt Renewal"
      day: "{{ letsencrypt_renewal_frequency.day }}"
      hour: "{{ letsencrypt_renewal_frequency.hour }}"
      minute: "{{ letsencrypt_renewal_frequency.minute }}"
      job: "{{ letsencrypt_venv }}/bin/letsencrypt renew --quiet {{ letsencrypt_renewal_command_args }}"
