---
  - name: Add jessie backports repository
    apt_repository:
      repo: deb http://ftp.debian.org/debian jessie-backports main
      state: present
    tags: install
    become: yes

  - name: Install certbot pin on jessie-backports
    apt:
      name: certbot
      state: present
      default_release: jessie-backports
    tags: install
    become: yes

  - name: Ensure webroot exists
    file:
      path: "{{ letsencrypt_webroot_path }}"
      state: directory
      follow: yes
    become: yes

  - name: Attempt to get the certificate using the webroot authenticator
    command: "{{ letsencrypt_command }} certonly"
    become: yes
    args:
      creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domains[0] }}"

